digitalpay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('home/', include('home.urls')),
    path('sms-panel/', include('sms_panel.urls')),
    path('installments/', include('installments.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
import uuid

from django.urls import path

from . import views

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

installments/urls.py
import uuid

from django.urls import path

from installments import views

urlpatterns = [
    path('', views.Installments.as_view(), name='installments'),
    path('api/<installment_id>/products/', views.Installment_products.as_view(), name='installment_products'),
    path('<installment_id>/', views.InstallmentDetail.as_view(), name='installment_detail'),
]

installments/models.py
import random

from django.db import models

from account.models import User


# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='نام کالا')
    count = models.IntegerField(verbose_name='تعداد')

    def __str__(self):
        return f"{self.name} ( {self.count} عدد )"


class Installment(models.Model):
    user = models.ForeignKey(User, verbose_name='کاربر', on_delete=models.CASCADE)
    product_name = models.ManyToManyField(to=Product, max_length=200, verbose_name='نام کالا')
    Installment_id = models.BigIntegerField(verbose_name='شناسه اقساط', unique=True, blank=True, auto_created=True, editable=False, db_index=True)
    amount = models.BigIntegerField(verbose_name='مبلغ')
    installments = models.IntegerField(verbose_name='تعداد اقساط', default=12)
    created_date = models.DateTimeField(verbose_name="تاریخ ایجاد", auto_now_add=True)
    is_done = models.BooleanField(verbose_name='اتمام اقساط', default=False)

    def __str__(self):
        return str(self.Installment_id)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.Installment_id is None:
            self.Installment_id = random.randint(1, 9999999999)
            return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)


class InstallmentDetail(models.Model):
    installments_info = models.ForeignKey(Installment, on_delete=models.CASCADE, verbose_name='اطلاعات اقساط')
    id_installment = models.BigIntegerField(verbose_name='شناسه قسط', unique=True, auto_created=True, editable=False, db_index=True)
    due_date = models.DateField(verbose_name='تاریخ سررسید')
    payment_date = models.DateField(verbose_name='تاریخ پرداخت', blank=True, null=True)
    amount = models.BigIntegerField(verbose_name='مبلغ هر قسط')
    is_paid = models.BooleanField(verbose_name='پرداخت شده', default=False)

    def __str__(self):
        return self.id_installment

installments/views.py
from django.contrib.auth import mixins
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views import View

from installments.models import Installment


# Create your views here.


class Installments(mixins.LoginRequiredMixin, View):
    def get(self, request):
        if request.user.is_superuser or request.user.is_staff:
            installments = Installment.objects.all().order_by('is_done')
        else:
            installments = Installment.objects.filter(user_id=request.user.id).order_by('is_done')
        return render(request, 'installments/installments.html', {
            'installments': installments,
        })


class Installment_products(mixins.LoginRequiredMixin, View):
    def get(self, request, installment_id):
        installment = get_object_or_404(Installment, Installment_id=installment_id)
        products = installment.product_name.all()
        product_list = [{'name': product.name, 'count': product.count} for product in products]
        return JsonResponse({
            'products': product_list
        })


class InstallmentDetail(mixins.LoginRequiredMixin, View):
    def get(self, request, installment_id):
        installment = get_object_or_404(Installment, Installment_id=installment_id, is_done=False)
        return render(request, 'installments/installment_detail.html', {
            'installment': installment
        })

installments/templates/installments/installment_detail.html
{% extends 'digitalpay/base.html' %}
{% load tags %}
{% load jalali_tags %}

{% block title %}
     لیست اقساط  {{ installment.Installment_id }}
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>لیست اقساط {{ installment.Installment_id }}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">صفحه نخست</a></li>
                            <li class="breadcrumb-item active">لیست اقساط {{ installment.Installment_id }}</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0" style="height: 660px;">
                                <table class="table table-head-fixed text-nowrap">
                                    <thead>
                                    <tr>
                                        <th>شناسه</th>
                                        <th>مبلغ</th>
                                        <th>تاریخ سر رسید</th>
                                        <th>تاریخ پرداخت</th>
                                        <th>وضعیت</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for ins in installment.installmentdetail_set.all %}
                                        <tr>
                                            <td>{{ ins.id_installment }}</td>
                                            <td>{{ ins.amount | three_digits_currency }}</td>
                                            <td>{{ ins.due_date | to_jalali:"%Y/%m/%d" }}</td>
                                            <td>
                                                {% if not ins.payment_date %}
                                                	-
                                                    {% else %}
                                                    {{ ins.payment_date | to_jalali:"%Y/%m/%d" }}
                                                {% endif %}
                                            </td>
                                            <td><span class="tag tag-success">
                                            {% if ins.is_paid %}
                                                <i class="fa fa-check" style="color: green"></i>&nbsp;<span style="color: green">پرداخت شده</span>
                                            {% else %}
                                                <i class="fa fa-times" style="color: red"></i>&nbsp;<span style="color: red">پرداخت نشده</span>
                                            {% endif %}
                                        </span></td>
                                            <td>
                                                {% if not ins.is_paid %}
                                                    <a href="#" class="btn btn-success"><i class="fa fa-credit-card mr-2"></i>پرداخت</a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

{% endblock %}

installments/templates/installments/installments.html
{% extends 'digitalpay/base.html' %}
{% load tags %}
{% load jalali_tags %}

{% block title %}
    لیست اقساط
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>لیست اقساط</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">صفحه نخست</a></li>
                            <li class="breadcrumb-item active">لیست اقساط</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0" style="height: 660px;">
                                {% if installments %}
                                    <table class="table table-head-fixed text-nowrap">
                                        <thead>
                                        <tr>
                                            <th>شناسه</th>
                                            <th>کاربر</th>
                                            <th>مبلغ</th>
                                            <th>تاریخ</th>
                                            <th>نام کالا</th>
                                            <th>تعداد اقساط</th>
                                            <th>وضعیت</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for installment in installments %}
                                            <tr>
                                                <td>{{ installment.Installment_id }}</td>
                                                <td>{{ installment.user.phone }}</td>
                                                <td>{{ installment.amount | three_digits_currency }}</td>
                                                <td>{{ installment.created_date | to_jalali:"%Y/%m/%d" }}</td>
                                                <td>
                                                    <div class="installment" data-installment-id="{{ installment.Installment_id }}">
                                                        <button type="button" class="btn btn-primary" id="btn-product" data-toggle="modal" data-target=".bd-example-modal-lg">مشاهده</button>
                                                        <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                                            <div class="modal-dialog modal-md">
                                                                <div class="modal-content">
                                                                    <div class="col-md-6 mt-4 mb-4" style="font-size: 12px">
                                                                        {% for product in installment.product_name.all %}
                                                                            <ul class="list-group" id="product_list"></ul>
                                                                        {% endfor %}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>{{ installment.installments }}</td>
                                                <td><span class="tag tag-success">
                                            {% if installment.is_done %}
                                                <i class="fa fa-check" style="color: green"></i>&nbsp;<span style="color: green">اتمام اقساط</span>
                                            {% else %}
                                                <i class="fa fa-radiation fa-spin" style="color: #0c84ff"></i>&nbsp;<span style="color: #0c84ff">در جریان</span>
                                            {% endif %}
                                        </span></td>
                                                <td>
                                                    {% if not installment.is_done %}
                                                        <a href="{% url 'installment_detail' installment.Installment_id %}" class="btn btn-primary">لیست اقساط</a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% endif %}
                                {% if not installments %}
                                    <table class="table table-head-fixed text-nowrap">
                                        <thead>
                                        <tr>
                                            <th>شناسه</th>
                                            <th>کاربر</th>
                                            <th>مبلغ</th>
                                            <th>تاریخ</th>
                                            <th>نام کالا</th>
                                            <th>تعداد اقساط</th>
                                            <th>وضعیت</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                    </table>
                                    <div class="mt-5 d-flex justify-content-center">
                                        <span class="alert alert-info">موردی برای نمایش وجود ندارد!</span>
                                    </div>
                                {% endif %}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

{% endblock %}